---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maesh-controller
  namespace: maesh
  labels:
    app: "maesh"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "maesh"
      component: "controller"
  template:
    metadata:
      labels:
        app: "maesh"
        component: "controller"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4646"
    spec:
      serviceAccountName: maesh-controller
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - controller
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: maesh-controller
          image: "containous/maesh:latest"
          imagePullPolicy: IfNotPresent
          args:
            - "--debug"
            - "--defaultMode=http"
            - "--namespace=$(POD_NAMESPACE)"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 200m
          ports:
            - name: api
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/status/readiness
              port: api
            initialDelaySeconds: 3
            periodSeconds: 1
      initContainers:
        - name: maesh-prepare
          image: "containous/maesh:latest"
          imagePullPolicy: IfNotPresent
          args:
            - "prepare"
            - "--debug"
            - "--clusterdomain"
            - "cluster.local"
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
