---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: maesh-controller
  namespace: maesh
  labels:
    app: "maesh"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: maesh-mesh
  namespace: maesh
  labels:
    app: "maesh"
automountServiceAccountToken: false
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: maesh-controller-role
  namespace: maesh
  labels:
    app: "maesh"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - update
      - create
  - apiGroups:
      - access.smi-spec.io
      - specs.smi-spec.io
      - split.smi-spec.io
    resources:
      - traffictargets
      - tcproutes
      - httproutegroups
      - trafficsplits
      - events
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: maesh-controller
  namespace: maesh
  labels:
    app: "maesh"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maesh-controller-role
subjects:
  - kind: ServiceAccount
    name: maesh-controller
    namespace: maesh
